<?php



return [
    'wonen' => [
        'serial_number' => 'product ID',
        'name' => 'name',
        'description' => 'description',
        'price' => 'price',
        'affiliate_link' => 'productURL',
        'currency' => 'currency',
        'category_path' => 'categoryPath',
        'brand' => 'brand',
        'delimiter' => ';',

        // Extra fields (nullable)
        'delivery_time' => 'deliveryTime',
        'sub_category' => 'subcategories',
        'sub_sub_category' => 'subsubcategories',
        'stock' => 'stock',
        'image_url' => 'imageURL',
        'from_price' => 'fromPrice',
        'material' => 'material',
        'reviews' => '',
        'rating' => '',
        'size' => '',
    ],
    'tech' => [
        'serial_number' => 'sku',
        'name' => 'product_name',
        'description' => 'product_summary',
        'price' => 'price',
        'affiliate_link' => 'product_url',
        'currency' => 'currency',
        'category_path' => 'category_path',
        'brand' => 'brand',
        'delimiter' => ',',

        // Extra fields (nullable)
        'delivery_time' => 'delivery_time',
        'sub_category' => 'product_type',
        'sub_sub_category' => 'subproducttypename',
        'stock' => 'product_availability_state_id',
        'image_url' => 'image_url',
        'from_price' => '',
        'material' => '',
        'reviews' => 'reviewscount',
        'rating' => 'reviewsaveragescore',
        'size' => '',
    ],
    'lezen' => [
        'serial_number' => 'product ID',
        'name' => 'name',
        'description' => 'description',
        'price' => 'price',
        'affiliate_link' => 'productURL',
        'currency' => 'currency',
        'category_path' => 'category_path',
        'brand' => 'brand',
        'delimiter' => ';',

        // Extra fields (nullable)
        'delivery_time' => '',
        'sub_category' => '',
        'sub_sub_category' => '',
        'stock' => '',
        'image_url' => 'imageURL',
        'from_price' => '',
        'material' => '',
        'reviews' => '',
        'rating' => '',
        'size' => '',
    ],
    'sport' => [
        'serial_number' => 'product ID',
        'name' => 'name',
        'description' => 'description',
        'price' => 'price',
        'image_url' => 'imageURL',
        'affiliate_link' => 'productURL',
        'currency' => 'currency',
        'category_path' => 'categoryPath',
        'delivery_time' => 'deliveryTime',
        'stock' => 'stock',
        'brand' => 'brand',
        'sub_category' => 'categories',
        'sub_sub_category' => 'subcategories',
        'size' => 'size',
        'delimiter' => ',',
    ]
];
